version: '3.1'

services:
  fastapi:
    build: ./dockerfiles/fastapi
    container_name: fastapi
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
      - ./nba-stats:/nba-stats
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  database:
    image: postgres:14.2-alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nba
    volumes:
      - ./nba-stats:/nba-stats
      # copy the sql script to create tables
      - ./sql-scripts/DDL_init.sql:/docker-entrypoint-initdb.d/DDL_init.sql
      # copy the sql script to fill tables
      - ./sql-scripts/DML_teams.sql:/docker-entrypoint-initdb.d/DML_teams.sql
    