version: '3.1'

services:
  fastapi:
    build: ./dockerfiles/fastapi
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
      - ./nba-stats:/nba-stats
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]